#!/usr/bin/env python3
"""GL-PAAS-001 deterministic structural court.

This verifier deliberately proves only source/pack closure. It cannot promote the
manufactured Elixir runtime to ALIVE; that requires canonical ggen + Mix execution.
"""
from __future__ import annotations

import hashlib
import json
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXPECTED = {
    "README.md",
    "pack.toml",
    "ggen.toml",
    "ontology.ttl",
    "gates/invalid-paas-model.rq",
    "gates/verify_pack.py",
    "queries/platform.rq",
    "templates/mix.exs.tera",
    "templates/lib/ggen_legacy_paas.ex.tera",
    "templates/test/ggen_legacy_paas_test.exs.tera",
}
PUBLIC_IRIS = {
    "https://schema.org/",
    "http://www.w3.org/ns/prov#",
    "http://www.w3.org/ns/dcat#",
    "http://purl.org/dc/terms/",
    "http://www.w3.org/ns/odrl/2/",
    "http://qudt.org/schema/qudt/",
    "http://www.w3.org/2004/02/skos/core#",
    "http://www.w3.org/ns/shacl#",
    "http://www.w3.org/ns/r2rml#",
}
GGEN_SHA = "1e9fcb9679a61460fbd641415cb72511c7e50b33"
ASH_R2RML_SHA = "067954ad406fd637fd47646bdb10c4580809c79d"


def fail(code: str, detail: str) -> None:
    raise SystemExit(f"REFUSED:{code}:{detail}")


def text(path: str) -> str:
    p = ROOT / path
    if not p.is_file():
        fail("MISSING_FILE", path)
    return p.read_text(encoding="utf-8")


def main() -> int:
    actual = {p.relative_to(ROOT).as_posix() for p in ROOT.rglob("*") if p.is_file()}
    missing = sorted(EXPECTED - actual)
    if missing:
        fail("INCOMPLETE_PACK", ",".join(missing))

    pack = tomllib.loads(text("pack.toml"))
    config = tomllib.loads(text("ggen.toml"))
    ontology = text("ontology.ttl")
    shapes = ontology
    gate = text("gates/invalid-paas-model.rq")
    runtime = text("templates/lib/ggen_legacy_paas.ex.tera")
    tests = text("templates/test/ggen_legacy_paas_test.exs.tera")
    mix = text("templates/mix.exs.tera")

    if pack["construction"]["ggen_sha"] != GGEN_SHA:
        fail("GGEN_IDENTITY_DRIFT", pack["construction"]["ggen_sha"])
    if pack["construction"]["ash_r2rml_sha"] != ASH_R2RML_SHA:
        fail("ASH_R2RML_IDENTITY_DRIFT", pack["construction"]["ash_r2rml_sha"])
    if ASH_R2RML_SHA not in mix:
        fail("UNPINNED_ASH_R2RML", "mix template does not bind exact ref")

    for iri in sorted(PUBLIC_IRIS):
        if iri not in ontology:
            fail("MISSING_PUBLIC_ONTOLOGY", iri)

    if "paas:brceRequired true" not in ontology or "paas:requestTimeGgen false" not in ontology:
        fail("AUTHORITY_FENCE_MISSING", "ontology must require BRCE and prohibit request-time ggen")
    if "sh:hasValue true" not in shapes or "sh:hasValue false" not in shapes:
        fail("SHACL_AUTHORITY_FENCE_MISSING", "expected boolean authority constraints")
    if "FILTER NOT EXISTS { ?profile paas:brceRequired true }" not in gate:
        fail("SPARQL_AUTHORITY_FENCE_MISSING", "BRCE refusal arm absent")
    if "FILTER NOT EXISTS { ?profile paas:requestTimeGgen false }" not in gate:
        fail("SPARQL_RUNTIME_FENCE_MISSING", "request-time ggen refusal arm absent")

    rules = config.get("generation", {}).get("rules", [])
    if len(rules) != 3:
        fail("GENERATION_SURFACE_DRIFT", f"expected 3 rules, got {len(rules)}")
    outputs = {rule["output_file"] for rule in rules}
    expected_outputs = {
        "consumer/paas/mix.exs",
        "consumer/paas/lib/ggen_legacy_paas.ex",
        "consumer/paas/test/ggen_legacy_paas_test.exs",
    }
    if outputs != expected_outputs:
        fail("OUTPUT_GRAPH_DRIFT", json.dumps(sorted(outputs)))
    for rule in rules:
        for key in ("query", "template"):
            ref = rule[key]["file"]
            if not (ROOT / ref).is_file():
                fail("DANGLING_GENERATOR_EDGE", ref)

    for name, body in {
        "mix": mix,
        "runtime": runtime,
        "tests": tests,
    }.items():
        if "@generated by ggen" not in body:
            fail("MISSING_PROVENANCE_HEADER", name)

    required_runtime = [
        "use Ash.Resource",
        "extensions: [AshR2RML.Resource]",
        "use Ash.Domain",
        "AshR2RML.compile_ash_ttl_bundle",
        "Reactor.run(AshR2RML.Reactor.Pipeline",
        "use Reactor",
        "defmodule {{ moduleName }}.BRCE",
        "brce.execute(",
        "UNRECEIPTED_ACTUATION",
        "UNBOUND_RECEIPT",
        "standing: :ALIVE",
    ]
    for needle in required_runtime:
        if needle not in runtime:
            fail("RUNTIME_CONTRACT_INCOMPLETE", needle)

    forbidden = [
        r"System\.cmd",
        r":os\.cmd",
        r"File\.(write|rm|cp|rename)",
        r"HTTPoison",
        r"Req\.",
        r"Finch\.",
        r"Tesla\.",
        r"ggen\s+sync",
    ]
    for pattern in forbidden:
        if re.search(pattern, runtime):
            fail("AMBIENT_ACTUATION_PATH", pattern)

    if runtime.count("brce.execute(") != 1:
        fail("DO_PATH_CARDINALITY", f"expected one BRCE call, got {runtime.count('brce.execute(')}")

    required_tests = [
        "first.files == second.files",
        "first.sha256 == second.sha256",
        "compile_reactor_mapping",
        "UnboundBRCE",
        "assert receipt.standing == :ALIVE",
        "refute contract.odrl_is_execution_authority?",
    ]
    for needle in required_tests:
        if needle not in tests:
            fail("TEST_CONTRACT_INCOMPLETE", needle)

    rows = []
    for rel in sorted(EXPECTED):
        data = (ROOT / rel).read_bytes()
        rows.append((rel, hashlib.sha256(data).hexdigest()))
    digest = hashlib.sha256(json.dumps(rows, separators=(",", ":")).encode()).hexdigest()
    receipt = {
        "case_id": "GL-PAAS-001",
        "ggen_sha": GGEN_SHA,
        "ash_r2rml_sha": ASH_R2RML_SHA,
        "files_verified": len(rows),
        "pack_sha256": digest,
        "standing": "PARTIAL_ALIVE",
        "scope": "source-pack-closure",
        "runtime_executed": False,
    }
    print(json.dumps(receipt, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
