(define (domain ggen-v2681-core)
  (:requirements :strips :typing :negative-preconditions :disjunctive-preconditions
    :equality :existential-preconditions :universal-preconditions
    :conditional-effects :derived-predicates :fluents :action-costs :preferences :constraints)
  (:types
    release subsystem stage artifact authority projection evidence receipt verifier
    capability command diagnostic schema pack bblock boundary legacy disposition standing)
  (:constants
    unknown partial-alive alive blocked build-broken unsupported - standing
    preserved subsumed replaced archived refused unknown-disposition - disposition)
  (:predicates
    (declared ?x - object)
    (observed ?x - object)
    (admitted ?x - object)
    (authoritative ?x - authority)
    (implements ?s - subsystem ?c - capability)
    (owned-by ?x - object ?s - subsystem)
    (depends-on ?a - object ?b - object)
    (projects ?p - projection ?a - artifact)
    (evidences ?e - evidence ?x - object)
    (verified-by ?x - object ?v - verifier)
    (positive-witness ?x - object)
    (negative-falsifier ?x - object)
    (replayable ?x - object)
    (deterministic ?x - object)
    (receipt-bound ?x - object ?r - receipt)
    (boundary-crossed ?b - boundary)
    (external-actuation ?x - object)
    (brce-admitted ?x - object)
    (legacy-capability ?c - capability)
    (legacy-disposition ?c - capability ?d - disposition)
    (standing-of ?x - object ?s - standing)
    (stage-precedes ?a - stage ?b - stage)
    (stage-complete ?s - stage)
    (release-candidate ?r - release)
    (release-admitted ?r - release)
    (sunset-admitted ?r - release)
    (information-loss ?c - capability)
    (conflict ?a - object ?b - object)
    (locked ?x - object)
    (changed ?x - object))
  (:functions
    (total-cost)
    (risk ?x - object)
    (coverage ?s - subsystem)
    (evidence-count ?x - object)
    (unresolved-count ?r - release)
    (rework ?x - object))
  (:derived (fully-evidenced ?x - object)
    (and (positive-witness ?x) (negative-falsifier ?x) (replayable ?x)
         (exists (?v - verifier) (verified-by ?x ?v))
         (exists (?r - receipt) (receipt-bound ?x ?r))))
  (:derived (sunset-safe ?r - release)
    (and (release-admitted ?r)
         (forall (?c - capability)
           (imply (legacy-capability ?c)
             (and (not (information-loss ?c))
                  (exists (?d - disposition)
                    (and (legacy-disposition ?c ?d)
                         (not (= ?d unknown-disposition)))))))))
  (:constraints
    (and
      (always (forall (?x - object) (imply (external-actuation ?x) (brce-admitted ?x))))
      (always (forall (?a ?b - object) (not (and (conflict ?a ?b) (admitted ?a) (admitted ?b)))))
      (sometime (exists (?r - release) (release-admitted ?r)))))

  (:action observe
    :parameters (?x - object)
    :precondition (and (declared ?x) (not (observed ?x)))
    :effect (and (observed ?x) (increase (total-cost) 1)))
  (:action admit
    :parameters (?x - object ?v - verifier ?r - receipt)
    :precondition (and (observed ?x) (verified-by ?x ?v) (receipt-bound ?x ?r)
      (positive-witness ?x) (negative-falsifier ?x) (replayable ?x)
      (not (exists (?y - object) (conflict ?x ?y))))
    :effect (and (admitted ?x) (standing-of ?x alive)
      (increase (evidence-count ?x) 3) (decrease (risk ?x) 1) (increase (total-cost) 2)))
  (:action bind-legacy-disposition
    :parameters (?c - capability ?d - disposition ?v - verifier ?r - receipt)
    :precondition (and (legacy-capability ?c) (not (= ?d unknown-disposition))
      (verified-by ?c ?v) (receipt-bound ?c ?r) (negative-falsifier ?c))
    :effect (and (legacy-disposition ?c ?d) (not (information-loss ?c))
      (increase (total-cost) 2)))
  (:action promote-release
    :parameters (?rel - release ?v - verifier ?r - receipt)
    :precondition (and (release-candidate ?rel) (= (unresolved-count ?rel) 0)
      (verified-by ?rel ?v) (receipt-bound ?rel ?r)
      (forall (?s - subsystem) (and (admitted ?s) (= (coverage ?s) 100))))
    :effect (and (release-admitted ?rel) (standing-of ?rel alive)
      (increase (total-cost) 10)))
  (:action admit-sunset
    :parameters (?rel - release)
    :precondition (sunset-safe ?rel)
    :effect (and (sunset-admitted ?rel) (increase (total-cost) 5)))
)
