(define (domain ggen-v2681-temporal)
  (:requirements :typing :negative-preconditions :equality :durative-actions
    :duration-inequalities :fluents :continuous-effects :derived-predicates
    :timed-initial-literals :preferences :constraints)
  (:types subsystem stage verifier resource receipt)
  (:predicates
    (ready ?s - subsystem)
    (running ?s - subsystem)
    (validated ?s - subsystem)
    (receipted ?s - subsystem ?r - receipt)
    (uses ?s - subsystem ?x - resource)
    (available ?x - resource)
    (precedes ?a - stage ?b - stage)
    (completed ?s - stage)
    (failed ?s - subsystem)
    (replayed ?s - subsystem))
  (:functions
    (remaining-work ?s - subsystem)
    (cpu-capacity ?x - resource)
    (io-capacity ?x - resource)
    (risk-load ?s - subsystem)
    (elapsed-verification)
    (total-cost))
  (:derived (crown-ready ?s - subsystem)
    (and (validated ?s) (replayed ?s)
      (exists (?r - receipt) (receipted ?s ?r))
      (= (remaining-work ?s) 0)))
  (:constraints
    (and
      (always (forall (?s - subsystem) (imply (running ?s) (not (failed ?s)))))
      (always-within 30 (forall (?s - subsystem) (imply (ready ?s) (validated ?s))))
      (at-most-once (exists (?s - subsystem) (failed ?s)))))
  (:durative-action verify-subsystem
    :parameters (?s - subsystem ?cpu - resource ?io - resource ?r - receipt)
    :duration (and (>= ?duration 1) (<= ?duration 120))
    :condition (and
      (at start (ready ?s))
      (at start (available ?cpu))
      (at start (available ?io))
      (over all (not (failed ?s)))
      (over all (> (cpu-capacity ?cpu) 0))
      (over all (> (io-capacity ?io) 0)))
    :effect (and
      (at start (running ?s))
      (at start (not (available ?cpu)))
      (at start (not (available ?io)))
      (increase (elapsed-verification) (* #t 1))
      (decrease (remaining-work ?s) (* #t 1))
      (at end (not (running ?s)))
      (at end (validated ?s))
      (at end (receipted ?s ?r))
      (at end (available ?cpu))
      (at end (available ?io))
      (at end (increase (total-cost) 1))))
  (:durative-action replay-subsystem
    :parameters (?s - subsystem ?cpu - resource)
    :duration (= ?duration 2)
    :condition (and (at start (validated ?s)) (over all (available ?cpu)))
    :effect (and (at start (not (available ?cpu)))
      (at end (available ?cpu)) (at end (replayed ?s))
      (at end (increase (total-cost) 1))))
)
