# legacy-equivalence-verifier-pack (generated consumer surface)

This directory is generated by `legacy-equivalence-verifier-pack` via `ggen sync run`. Do not
hand-edit `case_manifest.json`, `suites/verify-all.sh`, or `verifier-report.schema.json` --
edit `ontology.ttl` (or, in a downstream consumer, the real EquivalenceCase facts supplied by
the concurrent ontology-extraction agent) and re-run `ggen sync run`.

## What this pack proves at the G7 scaffolding stage

`case_manifest.json` is generated from `eqv:EquivalenceCase` RDF individuals in `ontology.ttl`
via `queries/cases.rq`. The individuals currently present are **synthetic examples**, not real
legacy-capability data -- see the notice at the top of `ontology.ttl`. Their purpose is to prove
the generation pipeline (RDF -> SPARQL -> Tera -> JSON manifest) is data-driven end to end, and
that the generic comparison engine (`tools/v26.8.1/equivalence_runner.py`, outside this pack,
reusable across every consumer) can execute a manifest of this shape and report PASS/FAIL with a
specific reason, without any per-case branches in the runner itself.

## Regenerating

```bash
cd packs/legacy-equivalence-verifier-pack
ggen sync run --dry-run   # preview
ggen sync run             # write consumer/legacy-equivalence/**
```

## Running the generated verifier

```bash
consumer/legacy-equivalence/suites/verify-all.sh \
  consumer/legacy-equivalence/case_manifest.json \
  /tmp/legacy-equivalence-report.json
```

`verify-all.sh` locates `tools/v26.8.1/equivalence_runner.py` by walking up from its own
location toward a repo root, or via the `EQV_RUNNER` environment variable override.
