//! Chicago-style CLI boundary proofs — GENERATED by chicago-tdd-tools-pack.
//!
//! Each `#[test]` dispatches through `run_boundary_spec` (the reusable,
//! real, compilable dispatch module in the sibling generated file
//! `chicago_tdd_tools_boundary_runtime.rs`, included below) which spawns a
//! real binary via `chicago_tdd_tools::cli_proof::CliHarness` and asserts
//! on observable exit codes and output. No mocks. No stubs. The binary must
//! exist on disk.

include!("chicago_tdd_tools_boundary_runtime.rs");

/// Covers: an explicit --root with no AGENTS.md anywhere up its ancestry still fails closed with repository root not found
#[test]
fn ggen_verifier_bad_root_fails_closed() {
    run_boundary_spec(&BoundarySpec {
        test_name: "ggen_verifier_bad_root_fails_closed",
        binary: "ggen-v26-8-1-verifier",
        args: "--root /tmp/definitely-not-a-repo",
        exit_code: 2,
        stdout_needle: None,
        stderr_needle: Some("repository root not found; pass --root <path>"),
    })
    .expect("boundary spec for ggen_verifier_bad_root_fails_closed");
}

/// Covers: with the resolve_root fix, an explicit correct --root gets past root resolution and fails later on a SEPARATE, still-unfixed bug: observe_workspace's unwrapped read of root/Cargo.toml, which does not exist at ggen-legacy's repo root
#[test]
fn ggen_verifier_good_root_gets_past_root_resolution() {
    run_boundary_spec(&BoundarySpec {
        test_name: "ggen_verifier_good_root_gets_past_root_resolution",
        binary: "ggen-v26-8-1-verifier",
        args: "--root /Users/sac/ggen-legacy",
        exit_code: 2,
        stdout_needle: None,
        stderr_needle: Some("v26.8.1 verifier refused: No such file or directory"),
    })
    .expect("boundary spec for ggen_verifier_good_root_gets_past_root_resolution");
}

/// Covers: receiptctl --help exits 0 with usage text
#[test]
fn receiptctl_help_lists_verbs() {
    run_boundary_spec(&BoundarySpec {
        test_name: "receiptctl_help_lists_verbs",
        binary: "receiptctl",
        args: "--help",
        exit_code: 0,
        stdout_needle: Some("Usage"),
        stderr_needle: None,
    })
    .expect("boundary spec for receiptctl_help_lists_verbs");
}

/// Covers: a known noun with an unrecognized verb exits nonzero with a clap error on stderr, distinct from an entirely-unknown top-level noun
#[test]
fn receiptctl_known_noun_unrecognized_verb_fails_closed() {
    run_boundary_spec(&BoundarySpec {
        test_name: "receiptctl_known_noun_unrecognized_verb_fails_closed",
        binary: "receiptctl",
        args: "algorithm frobnicate",
        exit_code: 1,
        stdout_needle: None,
        stderr_needle: Some("unrecognized subcommand"),
    })
    .expect("boundary spec for receiptctl_known_noun_unrecognized_verb_fails_closed");
}

/// Covers: an unrecognized flag on an otherwise-valid command exits nonzero with a clap error on stderr
#[test]
fn receiptctl_unexpected_flag_fails_closed() {
    run_boundary_spec(&BoundarySpec {
        test_name: "receiptctl_unexpected_flag_fails_closed",
        binary: "receiptctl",
        args: "algorithm list --bogus-flag",
        exit_code: 1,
        stdout_needle: None,
        stderr_needle: Some("unexpected argument"),
    })
    .expect("boundary spec for receiptctl_unexpected_flag_fails_closed");
}

/// Covers: an unknown subcommand exits nonzero with a clap error on stderr
#[test]
fn receiptctl_unknown_verb_fails_closed() {
    run_boundary_spec(&BoundarySpec {
        test_name: "receiptctl_unknown_verb_fails_closed",
        binary: "receiptctl",
        args: "frobnicate",
        exit_code: 1,
        stdout_needle: None,
        stderr_needle: Some("error"),
    })
    .expect("boundary spec for receiptctl_unknown_verb_fails_closed");
}

/// Covers: receiptctl --version exits 0 and prints a version string
#[test]
fn receiptctl_version_emits_name() {
    run_boundary_spec(&BoundarySpec {
        test_name: "receiptctl_version_emits_name",
        binary: "receiptctl",
        args: "--version",
        exit_code: 0,
        stdout_needle: Some("cli "),
        stderr_needle: None,
    })
    .expect("boundary spec for receiptctl_version_emits_name");
}

