#!/usr/bin/env bash
set -euo pipefail

# Generated by legacy-equivalence-verifier-pack (eqv:version 26.8.1).
# Invokes the GENERIC, data-driven equivalence_runner.py against the
# generated case_manifest.json. The runner itself lives outside this pack
# (tools/v26.8.1/equivalence_runner.py) because it is reusable across every
# consumer of this pack, not specific to any one manifest.

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MANIFEST="${1:-$HERE/case_manifest.json}"
REPORT="${2:-$HERE/VERIFIER_REPORT.json}"

# Locate equivalence_runner.py: prefer $EQV_RUNNER, then walk up looking for
# tools/v26.8.1/equivalence_runner.py (repo-root layout), then fall back to
# a copy alongside this suite if one was vendored in.
RUNNER="${EQV_RUNNER:-}"
if [[ -z "$RUNNER" ]]; then
  candidate_dir="$HERE"
  for _ in 1 2 3 4 5 6; do
    if [[ -f "$candidate_dir/tools/v26.8.1/equivalence_runner.py" ]]; then
      RUNNER="$candidate_dir/tools/v26.8.1/equivalence_runner.py"
      break
    fi
    candidate_dir="$(dirname "$candidate_dir")"
  done
fi
if [[ -z "$RUNNER" && -f "$HERE/equivalence_runner.py" ]]; then
  RUNNER="$HERE/equivalence_runner.py"
fi

if [[ -z "$RUNNER" || ! -f "$RUNNER" ]]; then
  echo "BLOCKED: could not locate equivalence_runner.py (set \$EQV_RUNNER to override)" 1>&2
  exit 2
fi

exec python3 "$RUNNER" --manifest "$MANIFEST" --report "$REPORT"
