#!/usr/bin/env python3
"""GENERATED by ggen. Edit authority/ecosystem-alive, not this projection."""
from __future__ import annotations

import argparse
import hashlib
import json
import shlex
import shutil
import subprocess
import time
from collections import defaultdict, deque
from pathlib import Path
from typing import Any

PROGRAM_NAME = "ggen Ecosystem ALIVE Program"
PROGRAM_VERSION = "1.0.0"
DEFAULT_MANIFEST = Path("authority/ecosystem-reconstitution/2026-07-31.repositories.json")
DEFAULT_STATE = Path("foundry/workstreams/state.json")
DEFAULT_EVIDENCE = Path("target/ecosystem-alive")
PROMOTION_OWNER = "verifiers/verify_ecosystem_alive.py"
TOOL_NAMES = ("git", "python3", "cargo", "rustc", "rustup", "node", "pnpm", "uv", "just", "ggen", "mdbook", "wasm-pack")
STANDINGS = ("ALIVE", "PARTIAL_ALIVE", "BLOCKED", "BUILD_BROKEN", "UNKNOWN", "UNSUPPORTED")


def canonical(value: Any) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()


def sha256(value: Any) -> str:
    return hashlib.sha256(canonical(value)).hexdigest()


def load_json(path: Path, default: Any = None) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def topo(repositories: list[dict[str, Any]]) -> list[str]:
    by_name = {item["repository"]: item for item in repositories}
    degree = {name: 0 for name in by_name}
    outgoing: dict[str, list[str]] = defaultdict(list)
    for name, item in by_name.items():
        for dependency in item.get("depends_on", []):
            if dependency not in by_name:
                raise SystemExit(f"unknown dependency {dependency} from {name}")
            degree[name] += 1
            outgoing[dependency].append(name)
    ready = deque(sorted(name for name, count in degree.items() if count == 0))
    order: list[str] = []
    while ready:
        current = ready.popleft()
        order.append(current)
        for target in sorted(outgoing[current]):
            degree[target] -= 1
            if degree[target] == 0:
                ready.append(target)
    if len(order) != len(by_name):
        raise SystemExit("repository dependency cycle")
    return order


def receipt_index(root: Path) -> dict[tuple[str, str], dict[str, Any]]:
    index: dict[tuple[str, str], dict[str, Any]] = {}
    if not root.exists():
        return index
    for path in sorted(root.rglob("*.json")):
        try:
            value = load_json(path)
        except (OSError, json.JSONDecodeError):
            continue
        if not isinstance(value, dict):
            continue
        repository = value.get("repository")
        kind = value.get("receipt_kind") or value.get("kind")
        if value.get("schema") == "ggen-legacy.source-reconstitution.receipt/v1":
            kind = "source"
        if repository and kind:
            value["_path"] = str(path)
            index[(str(repository), str(kind))] = value
    return index


def foundry_state(path: Path) -> dict[str, str]:
    value = load_json(path, {}) or {}
    return {key: cell.get("status", "UNKNOWN") for key, cell in value.get("workstreams", {}).items()}


def toolchain() -> dict[str, dict[str, Any]]:
    result: dict[str, dict[str, Any]] = {}
    for name in TOOL_NAMES:
        location = shutil.which(name)
        result[name] = {"available": bool(location), "path": location}
    return result


def repository_model(manifest: dict[str, Any], receipts: dict[tuple[str, str], dict[str, Any]]) -> list[dict[str, Any]]:
    by_name = {item["repository"]: item for item in manifest["repositories"]}
    rows: list[dict[str, Any]] = []
    for name in topo(manifest["repositories"]):
        item = by_name[name]
        kinds = {kind: receipts.get((name, kind)) for kind in ("source", "validation", "falsifier", "ggen", "replay")}
        if not item.get("product_reconstitution", True):
            standing = "UNSUPPORTED"
            blocker = "lineage-only transport; excluded from product promotion"
        elif not kinds["source"] or kinds["source"].get("standing") != "ALIVE":
            standing = "BLOCKED"
            blocker = "exact source receipt missing or non-ALIVE"
        elif not kinds["validation"]:
            standing = "PARTIAL_ALIVE"
            blocker = "repository-native validation receipt missing"
        elif kinds["validation"].get("standing") != "ALIVE":
            standing = kinds["validation"].get("standing", "BUILD_BROKEN")
            blocker = kinds["validation"].get("reason", "repository-native validation failed")
        elif not kinds["falsifier"] or kinds["falsifier"].get("standing") != "ALIVE":
            standing = "PARTIAL_ALIVE"
            blocker = "negative-control receipt missing"
        elif not kinds["ggen"] or kinds["ggen"].get("standing") != "ALIVE":
            standing = "PARTIAL_ALIVE"
            blocker = "ggen receipt missing"
        elif not kinds["replay"] or kinds["replay"].get("standing") != "ALIVE":
            standing = "PARTIAL_ALIVE"
            blocker = "clean replay receipt missing"
        else:
            standing = "ALIVE"
            blocker = None
        rows.append({
            "repository": name,
            "role": item["role"],
            "strategy": item["reconstruction_strategy"],
            "canonical_sha": item["canonical_reconstruction_sha"],
            "product": item.get("product_reconstitution", True),
            "depends_on": item.get("depends_on", []),
            "commands": item.get("validation_commands", []),
            "standing": standing,
            "blocker": blocker,
            "receipts": {kind: (value or {}).get("_path") for kind, value in kinds.items()},
        })
    return rows


def doctor_payload(args: argparse.Namespace) -> dict[str, Any]:
    manifest = load_json(args.manifest)
    if not isinstance(manifest, dict):
        raise SystemExit(f"manifest unavailable: {args.manifest}")
    receipts = receipt_index(args.receipts)
    rows = repository_model(manifest, receipts)
    state = foundry_state(args.state)
    tools = toolchain()
    counts = {standing: sum(1 for row in rows if row["standing"] == standing) for standing in STANDINGS}
    blockers: list[dict[str, str]] = []
    if state.get("C") == "ADMITTED" and Path(".github/workflows/foundry-c-diagnostic.yml").exists():
        blockers.append({"code": "QOL-IDEMPOTENCE-C", "message": "C is ADMITTED; diagnostic must remain a read-only no-op."})
    missing_tools = [name for name, item in tools.items() if not item["available"]]
    if missing_tools:
        blockers.append({"code": "DX-MISSING-TOOLS", "message": "Optional tools unavailable: " + ", ".join(missing_tools)})
    return {
        "schema": "ggen-legacy.ecosystem-alive.doctor/v1",
        "program": PROGRAM_NAME,
        "version": PROGRAM_VERSION,
        "manifest_digest": sha256(manifest),
        "repository_count": len(rows),
        "product_count": sum(1 for row in rows if row["product"]),
        "counts": counts,
        "foundry_workstreams": state,
        "tools": tools,
        "blockers": blockers,
        "repositories": rows,
        "promotion_owner": PROMOTION_OWNER,
        "aggregate_candidate": "ALIVE" if all(row["standing"] in {"ALIVE", "UNSUPPORTED"} for row in rows) else "PARTIAL_ALIVE",
        "promotion_granted": False,
    }


def print_table(rows: list[dict[str, Any]]) -> None:
    widths = {"repository": max([10] + [len(row["repository"]) for row in rows]), "standing": max([8] + [len(row["standing"]) for row in rows])}
    print(f"{'REPOSITORY':<{widths['repository']}}  {'STANDING':<{widths['standing']}}  NEXT")
    print(f"{'-' * widths['repository']}  {'-' * widths['standing']}  {'-' * 48}")
    for row in rows:
        next_text = row["blocker"] or "independent promotion eligible"
        print(f"{row['repository']:<{widths['repository']}}  {row['standing']:<{widths['standing']}}  {next_text}")


def next_row(payload: dict[str, Any]) -> dict[str, Any] | None:
    return next((row for row in payload["repositories"] if row["product"] and row["standing"] != "ALIVE"), None)


def validation_receipt(repo: dict[str, Any], workspace: Path, commands: list[str], results: list[dict[str, Any]], mode: str) -> dict[str, Any]:
    standing = "ALIVE" if results and all(result["exit_code"] == 0 for result in results) else "BUILD_BROKEN"
    core = {
        "schema": "ggen-legacy.ecosystem-alive.validation-receipt/v1",
        "receipt_kind": "validation",
        "repository": repo["repository"],
        "canonical_sha": repo["canonical_sha"],
        "workspace": str(workspace),
        "mode": mode,
        "commands": commands,
        "results": results,
        "standing": standing,
        "reason": None if standing == "ALIVE" else "one or more repository-native commands failed",
        "promotion_granted": False,
    }
    core["receipt_digest"] = "sha256:" + sha256(core)
    return core


def execute_repo(args: argparse.Namespace, payload: dict[str, Any]) -> int:
    row = next((item for item in payload["repositories"] if item["repository"] == args.repo), None)
    if not row:
        raise SystemExit(f"unknown repository: {args.repo}")
    workspace = args.workspace / row["repository"].split("/", 1)[1]
    commands = row["commands"][:1] if args.mode == "fast" else row["commands"]
    if not args.execute:
        print(json.dumps({"repository": row["repository"], "workspace": str(workspace), "commands": commands, "execute": False}, indent=2))
        return 0
    if not workspace.is_dir():
        print(f"workspace missing: {workspace}")
        return 2
    results: list[dict[str, Any]] = []
    for command in commands:
        started = time.monotonic()
        completed = subprocess.run(["bash", "-lc", command], cwd=workspace, text=True, capture_output=True, timeout=args.timeout)
        result = {
            "command": command,
            "exit_code": completed.returncode,
            "duration_ms": round((time.monotonic() - started) * 1000),
            "stdout_tail": completed.stdout[-4000:],
            "stderr_tail": completed.stderr[-4000:],
        }
        results.append(result)
        if completed.returncode != 0 and not args.keep_going:
            break
    receipt = validation_receipt(row, workspace, commands, results, args.mode)
    path = args.receipts / "validation" / (row["repository"].replace("/", "__") + ".json")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(canonical(receipt) + b"\n")
    print(json.dumps(receipt, indent=2, sort_keys=True))
    return 0 if receipt["standing"] == "ALIVE" else 4


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="ecosystem-doctor", description=PROGRAM_NAME)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--state", type=Path, default=DEFAULT_STATE)
    parser.add_argument("--receipts", type=Path, default=DEFAULT_EVIDENCE / "receipts")
    parser.add_argument("--json", action="store_true")
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("doctor")
    sub.add_parser("status")
    plan = sub.add_parser("plan")
    plan.add_argument("--mode", choices=("fast", "full"), default="fast")
    explain = sub.add_parser("explain")
    explain.add_argument("repo")
    sub.add_parser("resume")
    matrix = sub.add_parser("matrix")
    matrix.add_argument("--mode", choices=("fast", "full"), default="fast")
    run = sub.add_parser("run")
    run.add_argument("--repo", required=True)
    run.add_argument("--mode", choices=("fast", "full"), default="fast")
    run.add_argument("--workspace", type=Path, default=DEFAULT_EVIDENCE / "workspaces")
    run.add_argument("--execute", action="store_true")
    run.add_argument("--keep-going", action="store_true")
    run.add_argument("--timeout", type=int, default=1800)
    sub.add_parser("verify")
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    payload = doctor_payload(args)
    if args.command == "run":
        return execute_repo(args, payload)
    if args.command == "status":
        if args.json:
            print(json.dumps(payload["repositories"], indent=2, sort_keys=True))
        else:
            print_table(payload["repositories"])
        return 0
    if args.command == "doctor":
        if args.json:
            print(json.dumps(payload, indent=2, sort_keys=True))
        else:
            print(f"{PROGRAM_NAME} v{PROGRAM_VERSION}")
            print_table(payload["repositories"])
            print("\nFoundry:", " ".join(f"{key}={value}" for key, value in sorted(payload["foundry_workstreams"].items())))
            print("Aggregate candidate:", payload["aggregate_candidate"], "(promotion not granted)")
        return 0 if payload["aggregate_candidate"] == "ALIVE" else 2
    if args.command == "plan":
        limit = 1 if args.mode == "fast" else None
        plan = [{"repository": row["repository"], "canonical_sha": row["canonical_sha"], "commands": row["commands"][:limit]} for row in payload["repositories"] if row["product"]]
        print(json.dumps({"schema": "ggen-legacy.ecosystem-alive.plan/v1", "mode": args.mode, "cells": plan, "digest": sha256(plan)}, indent=2, sort_keys=True))
        return 0
    if args.command == "matrix":
        limit = 1 if args.mode == "fast" else None
        include = [{"repository": row["repository"], "repo_name": row["repository"].split("/", 1)[1], "sha": row["canonical_sha"], "mode": args.mode, "commands": row["commands"][:limit]} for row in payload["repositories"] if row["product"]]
        print(json.dumps({"include": include}, separators=(",", ":")))
        return 0
    if args.command == "explain":
        row = next((item for item in payload["repositories"] if item["repository"] == args.repo), None)
        if not row:
            raise SystemExit(f"unknown repository: {args.repo}")
        if args.json:
            print(json.dumps(row, indent=2, sort_keys=True))
        else:
            print(f"{row['repository']}\n  standing: {row['standing']}\n  blocker: {row['blocker']}\n  source: {row['canonical_sha']}\n  role: {row['role']}\n  next: python3 tools/ecosystem-doctor.py run --repo {shlex.quote(row['repository'])} --mode fast --execute")
        return 0
    if args.command == "resume":
        row = next_row(payload)
        if not row:
            print(f"All product repositories have candidate ALIVE receipts. Run {PROMOTION_OWNER}.")
            return 0
        print(f"python3 tools/ecosystem-doctor.py explain {shlex.quote(row['repository'])}")
        print(f"python3 tools/ecosystem-doctor.py run --repo {shlex.quote(row['repository'])} --mode fast --execute")
        return 2
    if args.command == "verify":
        print(json.dumps({"schema": "ggen-legacy.ecosystem-alive.candidate-verification/v1", "candidate": payload["aggregate_candidate"], "promotion_granted": False, "promotion_owner": PROMOTION_OWNER, "digest": sha256(payload["repositories"])}, indent=2, sort_keys=True))
        return 0 if payload["aggregate_candidate"] == "ALIVE" else 2
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
