(define (domain ggen-legacy-v26-9-28-fond)
 (:requirements :strips :non-deterministic)
 (:predicates (admitted) (manufactured) (verified) (receipted) (replayed) (failed-edge) (released))
 (:action manufacture :precondition (admitted) :effect (oneof (manufactured) (failed-edge)))
 (:action verify :precondition (manufactured) :effect (oneof (verified) (failed-edge)))
 (:action receipt :precondition (verified) :effect (receipted))
 (:action replay :precondition (receipted) :effect (oneof (replayed) (failed-edge)))
 (:action release :precondition (replayed) :effect (released))
)
