//! GENERATED by ggen from `self-host/lsp-contract/ontology.ttl`.
//! Edit the ontology and rerun the self-host contract projection.

pub const CONTRACT_VERSION: &str = "26.8.5";
pub const CONTRACT_SCHEMA: &str = "ggen.lsp.contract/1";
pub const GGEN_SRC_004: &str = "GGEN-SRC-004";

pub const REQUIRED_METHODS: &[&str] = &[
    "initialize",
    "initialized",
    "shutdown",
    "exit",
    "textDocument/didOpen",
    "textDocument/didChange",
    "textDocument/didSave",
    "textDocument/didClose",
    "textDocument/completion",
    "textDocument/hover",
    "textDocument/definition",
    "textDocument/references",
    "textDocument/prepareRename",
    "textDocument/rename",
    "textDocument/documentSymbol",
    "workspace/symbol",
    "textDocument/formatting",
    "textDocument/rangeFormatting",
    "textDocument/codeAction",
    "textDocument/foldingRange",
    "textDocument/semanticTokens/full",
    "textDocument/inlayHint",
    "textDocument/codeLens",
    "textDocument/prepareCallHierarchy",
    "callHierarchy/incomingCalls",
    "callHierarchy/outgoingCalls",
    "textDocument/prepareTypeHierarchy",
    "typeHierarchy/supertypes",
    "typeHierarchy/subtypes",
];

pub const REQUIRED_SURFACES: &[&str] = &[
    "ttl",
    "nt",
    "nq",
    "rq",
    "sparql",
    "tera",
    "toml",
    "rs",
];

pub const DECLARED_DIAGNOSTICS: &[&str] = &[
    "GGEN-SRC-004",
    "GGEN-TPL-001",
    "GGEN-RULE-001",
    "GGEN-OUT-001",
    "GGEN-HARNESS-001",
    "GGEN-TOML-001",
    "GGEN-MANIFEST-001",
    "GGEN-TTL-001",
    "GGEN-TERA-001",
    "GGEN-SPARQL-001",
    "GGEN-RDF-001",
];

#[must_use]
pub fn has_method(method: &str) -> bool {
    REQUIRED_METHODS.contains(&method)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_contract_is_sorted_and_unique() {
        let mut methods = REQUIRED_METHODS.to_vec();
        methods.sort_unstable();
        methods.dedup();
        assert_eq!(methods.len(), REQUIRED_METHODS.len());
        assert_eq!(REQUIRED_METHODS.len(), 29);
        assert_eq!(REQUIRED_SURFACES.len(), 8);
        assert_eq!(DECLARED_DIAGNOSTICS.len(), 11);
    }
}
