#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::needless_raw_string_hashes,
    clippy::duration_suboptimal_units,
    clippy::branches_sharing_code,
    clippy::used_underscore_binding,
    clippy::single_char_pattern,
    clippy::ignore_without_reason,
    clippy::cloned_ref_to_slice_refs,
    clippy::doc_overindented_list_items,
    clippy::match_wildcard_for_single_variants,
    clippy::ignored_unit_patterns,
    clippy::needless_collect,
    clippy::unnecessary_map_or,
    clippy::manual_flatten,
    clippy::manual_strip,
    clippy::future_not_send,
    clippy::unnested_or_patterns,
    clippy::no_effect_underscore_binding,
    clippy::literal_string_with_formatting_args
)]
//! Tests for Tera template inheritance ({% extends %}, {% include %}, {% block %})
//!
//! These tests verify that:
//! 1. The base `_head.tera` template parses without error
//! 2. Child templates correctly extend `_head.tera` via `{% extends %}`
//! 3. Block overrides produce valid merged output (header + imports + body)
//! 4. Missing base template causes a Tera error (not a panic)
//! 5. All child templates in `mcp-server/` parse and extend correctly
//! 6. `{% include %}` templates resolve correctly (benchmark components)
//! 7. No circular `{% extends %}` chains exist across the template tree
//!
//! NOTE: Tera validates `{% extends %}` at `add_raw_template` time, so the parent
//! template must be registered before the child. Similarly, `{% include %}` targets
//! must be registered before the template that includes them.

use std::collections::HashMap;
use tera::{Context, Tera};
use walkdir::WalkDir;

fn workspace_root() -> std::path::PathBuf {
    let mut p = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.pop(); // crates/ggen-core -> crates
    p.pop(); // crates -> ggen root
    p
}

/// Read a template file relative to the ggen workspace root, returning None if missing.
fn read_template(rel: &str) -> Option<String> {
    let path = workspace_root().join(rel);
    if !path.exists() {
        return None;
    }
    Some(
        std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("Cannot read {}: {}", path.display(), e)),
    )
}

/// Create a Tera instance with all ggen-core filters/functions registered.
fn create_tera() -> Tera {
    let mut tera = Tera::default();
    ggen_core::register::register_all(&mut tera);
    tera
}

// ---------------------------------------------------------------------------
// Test 1: _head.tera base template parses without error
// ---------------------------------------------------------------------------

#[test]
fn test_base_head_template_parses_without_error() {
    let content = read_template("crates/ggen-core/templates/mcp-server/_head.tera");
    if content.is_none() {
        return; // gracefully skip if template doesn't exist
    }
    let content = content.unwrap();

    let mut tera = create_tera();
    tera.add_raw_template("mcp-server/_head.tera", &content)
        .expect("_head.tera should parse without error");

    // Verify it renders with a minimal context (all vars use defaults)
    let mut ctx = Context::new();
    ctx.insert("file_description", "Test base template");
    let result = tera.render("mcp-server/_head.tera", &ctx);
    assert!(
        result.is_ok(),
        "_head.tera render failed: {:?}",
        result.err()
    );

    let output = result.unwrap();
    assert!(output.contains("Test base template"));
    assert!(output.contains("Generated by ggen"));
}

// ---------------------------------------------------------------------------
// Test 2: Child templates extend _head.tera correctly
// ---------------------------------------------------------------------------

#[test]
fn test_stdio_server_extends_head_correctly() {
    let head = read_template("crates/ggen-core/templates/mcp-server/_head.tera");
    let child = read_template("crates/ggen-core/templates/mcp-server/stdio_server.rs.tera");
    if head.is_none() || child.is_none() {
        return;
    }

    let mut tera = create_tera();
    // Parent MUST be loaded before child (Tera validates extends at parse time)
    tera.add_raw_template("mcp-server/_head.tera", &head.unwrap())
        .expect("_head.tera should parse");
    tera.add_raw_template("mcp-server/stdio_server.rs.tera", &child.unwrap())
        .expect("stdio_server.rs.tera should parse with parent loaded");

    let mut ctx = Context::new();
    ctx.insert("server_type", "McpServer");
    ctx.insert("buffer_size", &65536u64);
    ctx.insert("line_timeout_ms", &30000u64);
    ctx.insert("error_type", "McpError");
    ctx.insert("file_description", "STDIO transport for MCP");
    ctx.insert("spec_uri", "test://spec");
    ctx.insert("generation_timestamp", "2026-03-29T00:00:00Z");
    ctx.insert("idempotent", &true);

    let result = tera.render("mcp-server/stdio_server.rs.tera", &ctx);
    assert!(result.is_ok(), "stdio render failed: {:?}", result.err());

    let output = result.unwrap();

    // Base template content (header block)
    assert!(
        output.contains("STDIO transport for MCP"),
        "output should contain file_description from header block"
    );
    assert!(
        output.contains("Generated by ggen from: test://spec"),
        "output should contain spec_uri from header block"
    );
    assert!(
        output.contains("SDK: rmcp 1.3.0"),
        "output should contain SDK line from header block"
    );

    // Base template content (imports block)
    assert!(
        output.contains("use serde::{Deserialize, Serialize}"),
        "output should contain base imports from _head.tera"
    );
    assert!(
        output.contains("use rmcp::"),
        "output should contain rmcp imports from _head.tera"
    );

    // Child-specific imports (super() + own)
    assert!(
        output.contains("use rmcp::{ServiceExt, service::RunningService}"),
        "output should contain child's extra imports"
    );
    assert!(
        output.contains("use std::sync::atomic"),
        "output should contain child's atomic imports"
    );

    // Child-specific body content
    assert!(
        output.contains("pub struct StdioServer"),
        "output should contain StdioServer struct from child body block"
    );
    assert!(
        output.contains("pub struct AsyncStdioServer"),
        "output should contain AsyncStdioServer from child body block"
    );
    assert!(
        output.contains("pub struct StdioConfig"),
        "output should contain StdioConfig from child body block"
    );
}

// ---------------------------------------------------------------------------
// Test 3: Block overrides produce valid merged output (no Tera artifacts)
// ---------------------------------------------------------------------------

#[test]
fn test_block_overrides_produce_clean_merged_output() {
    let head = read_template("crates/ggen-core/templates/mcp-server/_head.tera");
    let child = read_template("crates/ggen-core/templates/mcp-server/mcp_server.rs.tera");
    if head.is_none() || child.is_none() {
        return;
    }

    let mut tera = create_tera();
    tera.add_raw_template("mcp-server/_head.tera", &head.unwrap())
        .expect("_head.tera should parse");
    tera.add_raw_template("mcp-server/mcp_server.rs.tera", &child.unwrap())
        .expect("mcp_server.rs.tera should parse with parent loaded");

    let mut ctx = Context::new();
    ctx.insert("server_name", "TestMcpServer");
    ctx.insert("server_version", "1.0.0");
    ctx.insert("server_description", "Test server");
    ctx.insert("transport_type", "stdio");
    ctx.insert("file_description", "MCP server implementation");
    ctx.insert("spec_uri", "test://spec");
    ctx.insert("generation_timestamp", "2026-03-29T00:00:00Z");
    ctx.insert("idempotent", &true);

    let result = tera.render("mcp-server/mcp_server.rs.tera", &ctx);
    assert!(
        result.is_ok(),
        "mcp_server render failed: {:?}",
        result.err()
    );

    let output = result.unwrap();

    // Header block content (from base)
    assert!(
        output.contains("MCP server implementation"),
        "merged output should have header content"
    );

    // Imports block content (child calls super() then adds own)
    assert!(
        output.contains("use crate::mcp::tool_registry::McpToolRegistry"),
        "child imports should appear after super()"
    );

    // Body block content (child override)
    assert!(
        output.contains("pub struct TestMcpServer"),
        "body block should render server_name as PascalCase"
    );
    assert!(
        output.contains("pub struct ServerConfig"),
        "body block should contain ServerConfig"
    );

    // No Tera template artifacts should leak
    assert!(
        !output.contains("{{"),
        "rendered output should not contain unclosed expressions"
    );
    assert!(
        !output.contains("{%"),
        "rendered output should not contain unrendered template tags"
    );
}

// ---------------------------------------------------------------------------
// Test 4: Missing base template causes Tera error (not a panic)
// ---------------------------------------------------------------------------

#[test]
fn test_missing_base_template_causes_tera_error() {
    let child = read_template("crates/ggen-core/templates/mcp-server/stdio_server.rs.tera");
    if child.is_none() {
        return;
    }

    // Load child WITHOUT the base template. Tera validates extends at
    // add_raw_template time, so this should return an Err, not panic.
    let mut tera = create_tera();
    let result = tera.add_raw_template("mcp-server/stdio_server.rs.tera", &child.unwrap());

    assert!(
        result.is_err(),
        "loading child without parent should return an error, not succeed"
    );

    let err_msg = format!("{:?}", result.unwrap_err());
    assert!(
        err_msg.contains("mcp-server/_head.tera")
            || err_msg.contains("not found")
            || err_msg.contains("unexpected tag"),
        "error should reference the missing parent template, got: {}",
        err_msg
    );
}

// ---------------------------------------------------------------------------
// Test 5: All child templates in mcp-server/ parse and extend correctly
// ---------------------------------------------------------------------------

#[test]
fn test_all_mcp_server_children_extend_head() {
    let root = workspace_root();
    let mcp_dir = root.join("crates/ggen-core/templates/mcp-server");
    if !mcp_dir.exists() {
        return;
    }

    let mut tera = create_tera();

    // Load base template first (required before any child)
    let head_path = mcp_dir.join("_head.tera");
    if !head_path.exists() {
        return;
    }
    let head_content = std::fs::read_to_string(&head_path).unwrap();
    tera.add_raw_template("mcp-server/_head.tera", &head_content)
        .expect("_head.tera should parse");

    // Collect all child templates
    let mut children: Vec<std::path::PathBuf> = Vec::new();
    for entry in WalkDir::new(&mcp_dir)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().is_some_and(|ext| ext == "tera"))
    {
        // Skip the base template itself
        if entry.file_name() == "_head.tera" {
            continue;
        }
        children.push(entry.path().to_path_buf());
    }

    assert!(
        !children.is_empty(),
        "should find child templates in mcp-server/"
    );

    let mut errors = Vec::new();
    let mut checked = 0usize;

    for child_path in &children {
        let content = match std::fs::read_to_string(child_path) {
            Ok(c) => c,
            Err(e) => {
                errors.push(format!("READ ERROR {}: {}", child_path.display(), e));
                continue;
            }
        };

        // Every child MUST extend _head.tera
        assert!(
            content.contains("{% extends \"mcp-server/_head.tera\" %}"),
            "child template {} must extend mcp-server/_head.tera",
            child_path.display()
        );

        // Register with the correct name that {% extends %} references
        let template_name = format!(
            "mcp-server/{}",
            child_path.file_name().unwrap().to_str().unwrap()
        );

        if let Err(e) = tera.add_raw_template(&template_name, &content) {
            errors.push(format!("PARSE ERROR in {}: {}", child_path.display(), e));
        } else {
            checked += 1;
        }
    }

    if !errors.is_empty() {
        panic!(
            "mcp-server child template errors ({} of {} checked):\n{}",
            errors.len(),
            children.len(),
            errors.join("\n")
        );
    }

    assert_eq!(
        checked,
        children.len(),
        "all {} child templates should parse successfully",
        children.len()
    );
}

// ---------------------------------------------------------------------------
// Test 6: {% include %} templates resolve correctly (benchmark components)
// ---------------------------------------------------------------------------

#[test]
fn test_benchmark_include_templates_resolve() {
    let root = workspace_root();
    let components_dir = root.join("crates/ggen-core/templates/benchmark_components");
    if !components_dir.exists() {
        return;
    }

    // Verify the benchmark_components directory exists and has templates
    let tera_files: Vec<std::path::PathBuf> = WalkDir::new(&components_dir)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().is_some_and(|ext| ext == "tera"))
        .map(|e| e.path().to_path_buf())
        .collect();

    assert!(
        !tera_files.is_empty(),
        "should find .tera files in benchmark_components/"
    );

    // Load the macro-only component files that are known to parse cleanly.
    // Some benchmark component templates have pre-existing syntax issues
    // (e.g., Jinja2-style {{{ }}} triple-brace syntax) that are outside
    // the scope of inheritance testing. We only test the clean ones.
    let mut tera = create_tera();
    let mut loaded_count = 0usize;
    let mut parse_errors = Vec::new();

    // Files known to parse cleanly with Tera
    let clean_macro_files = [
        "benchmark_setup.tera",
        "benchmark_teardown.tera",
        "benchmark_data_gen.tera",
        "benchmark_assertions.tera",
    ];

    for macro_file in &clean_macro_files {
        let path = components_dir.join(macro_file);
        if !path.exists() {
            continue;
        }

        let content = match std::fs::read_to_string(&path) {
            Ok(c) => c,
            Err(e) => {
                parse_errors.push(format!("READ ERROR {}: {}", path.display(), e));
                continue;
            }
        };

        let name = format!("benchmark_components/{}", macro_file);
        if let Err(e) = tera.add_raw_template(&name, &content) {
            parse_errors.push(format!("PARSE ERROR in {}: {}", macro_file, e));
        } else {
            loaded_count += 1;
        }
    }

    assert!(
        !parse_errors.is_empty() || loaded_count > 0,
        "should either load some templates or have documented parse errors"
    );

    // Report pre-existing parse issues as warnings (not failures)
    for err in &parse_errors {
        eprintln!("[WARN] {}", err);
    }

    assert!(
        loaded_count >= 2,
        "should load at least 2 clean macro benchmark component templates, loaded {}",
        loaded_count
    );

    // Now test {% include %} resolution: load the Go benchmark parent template.
    // This template uses {% include "benchmark_components/benchmark_setup.tera" %} etc.
    // The includes should resolve without "template not registered" errors.
    let go_bench = read_template(
        "crates/ggen-core/templates/benchmark_components/refactored_sparql_benchmark.go.tera",
    );
    if let Some(content) = go_bench {
        let result = tera.add_raw_template(
            "benchmark_components/refactored_sparql_benchmark.go.tera",
            &content,
        );

        // The Go template may fail to parse if it references macros from
        // component files that themselves have parse errors. But it should
        // NOT fail with "template not registered" for the includes.
        if let Err(e) = &result {
            let err_str = format!("{:?}", e);
            assert!(
                !err_str.contains("is not a registered template"),
                "should not get unresolved include error, got: {}",
                err_str
            );
        }
    }

    // Test Elixir benchmark template {% include %} resolution
    let exs_bench = read_template(
        "crates/ggen-core/templates/benchmark_components/refactored_sparql_benchmark_simple.exs.tera",
    );
    if let Some(content) = exs_bench {
        let result = tera.add_raw_template(
            "benchmark_components/refactored_sparql_benchmark_simple.exs.tera",
            &content,
        );

        if let Err(e) = &result {
            let err_str = format!("{:?}", e);
            // Should NOT fail with unresolved include
            assert!(
                !err_str.contains("is not a registered template"),
                "Elixir benchmark should not fail with unresolved include, got: {}",
                err_str
            );
        }
    }
}

// ---------------------------------------------------------------------------
// Test 7: No circular {% extends %} chains
// ---------------------------------------------------------------------------

#[test]
fn test_no_circular_extends_chains() {
    let root = workspace_root();
    let templates_dir = root.join("crates/ggen-core/templates");
    if !templates_dir.exists() {
        return;
    }

    // Collect all .tera files and their {% extends "..." %} directives
    let mut extends_map: HashMap<String, String> = HashMap::new();

    for entry in WalkDir::new(&templates_dir)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().is_some_and(|ext| ext == "tera"))
    {
        let content = match std::fs::read_to_string(entry.path()) {
            Ok(c) => c,
            Err(_) => continue,
        };

        // Extract the {% extends "..." %} directive
        let extends_target = extract_extends(&content);
        if let Some(target) = extends_target {
            let key = entry
                .path()
                .strip_prefix(&root)
                .unwrap()
                .to_str()
                .unwrap()
                .to_string();
            extends_map.insert(key, target);
        }
    }

    // For each template that extends another, follow the chain looking for cycles
    let mut errors = Vec::new();

    for (template, parent) in &extends_map {
        let mut visited = vec![template.as_str()];
        let mut current = parent.as_str();

        loop {
            // Check for cycle
            if visited.contains(&current) {
                errors.push(format!(
                    "Circular extends chain detected: {} -> {} (revisits {})",
                    visited.join(" -> "),
                    current,
                    current
                ));
                break;
            }

            // Check if current has an extends
            if let Some(next_parent) = extends_map.get(current) {
                visited.push(current);
                current = next_parent;
            } else {
                // Reached a root template (no extends) — chain is valid
                break;
            }
        }
    }

    if !errors.is_empty() {
        panic!("Circular extends chains detected:\n{}", errors.join("\n"));
    }
}

/// Extract the target template name from a `{% extends "..." %}` directive.
/// Returns None if the template doesn't extend anything.
fn extract_extends(content: &str) -> Option<String> {
    for line in content.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("{% extends") {
            // Find the quoted string
            if let Some(start) = rest.find('"') {
                let after_start = &rest[start + 1..];
                if let Some(end) = after_start.find('"') {
                    return Some(after_start[..end].to_string());
                }
            }
        }
    }
    None
}

// ---------------------------------------------------------------------------
// Additional: Verify resource_handler extends _head.tera and renders
// ---------------------------------------------------------------------------

#[test]
fn test_resource_handler_extends_head_and_renders() {
    let head = read_template("crates/ggen-core/templates/mcp-server/_head.tera");
    let child = read_template("crates/ggen-core/templates/mcp-server/resource_handler.rs.tera");
    if head.is_none() || child.is_none() {
        return;
    }

    let mut tera = create_tera();
    tera.add_raw_template("mcp-server/_head.tera", &head.unwrap())
        .expect("_head.tera should parse");
    tera.add_raw_template("mcp-server/resource_handler.rs.tera", &child.unwrap())
        .expect("resource_handler.rs.tera should parse with parent loaded");

    let mut ctx = Context::new();
    ctx.insert("resource_type", "Resource");
    ctx.insert("cache_entry_type", "CacheEntry");
    ctx.insert("error_type", "McpError");
    ctx.insert("resource_response_type", "String");
    // Empty resources array (no for-loop iterations)
    let resources: Vec<serde_json::Value> = vec![];
    ctx.insert("resources", &resources);
    ctx.insert("file_description", "Resource handler");
    ctx.insert("idempotent", &true);

    let result = tera.render("mcp-server/resource_handler.rs.tera", &ctx);
    assert!(
        result.is_ok(),
        "resource_handler render failed: {:?}",
        result.err()
    );

    let output = result.unwrap();

    // Base header content
    assert!(output.contains("Resource handler"));
    assert!(output.contains("SDK: rmcp 1.3.0"));

    // Base imports (from super())
    assert!(output.contains("use serde::{Deserialize, Serialize}"));
    assert!(output.contains("use rmcp::"));

    // Child imports
    assert!(output.contains("use std::collections::HashMap"));
    assert!(output.contains("use tokio::io::"));

    // Child body
    assert!(output.contains("pub struct ResourceHandler"));
    assert!(output.contains("pub struct CacheStats"));
    assert!(output.contains("fn uri_matches_pattern"));
}

// ---------------------------------------------------------------------------
// Additional: Verify tool_handler extends _head.tera with SPARQL data
// ---------------------------------------------------------------------------

#[test]
fn test_tool_handler_extends_head_and_renders_with_sparql_data() {
    let head = read_template("crates/ggen-core/templates/mcp-server/_head.tera");
    let child = read_template("crates/ggen-core/templates/mcp-server/tool_handler.rs.tera");
    if head.is_none() || child.is_none() {
        return;
    }

    let mut tera = create_tera();
    tera.add_raw_template("mcp-server/_head.tera", &head.unwrap())
        .expect("_head.tera should parse");
    tera.add_raw_template("mcp-server/tool_handler.rs.tera", &child.unwrap())
        .expect("tool_handler.rs.tera should parse with parent loaded");

    let mut ctx = Context::new();
    ctx.insert("tool_name", "get_user");
    ctx.insert("server_name", "UserMcpServer");
    ctx.insert("file_description", "Tool handler for user tools");
    ctx.insert("idempotent", &true);

    // Provide mock SPARQL results (one row for the get_user tool with one param)
    let sparql_results = serde_json::json!([
        {
            "tool_name": "get_user",
            "tool_description": "Get user by ID",
            "param_name": "user_id",
            "param_description": "The user identifier",
            "is_required": "true",
            "rust_type": "String"
        }
    ]);
    ctx.insert("sparql_results", &sparql_results);

    let result = tera.render("mcp-server/tool_handler.rs.tera", &ctx);
    assert!(
        result.is_ok(),
        "tool_handler render failed: {:?}",
        result.err()
    );

    let output = result.unwrap();

    // Base header
    assert!(output.contains("Tool handler for user tools"));
    assert!(output.contains("SDK: rmcp 1.3.0"));

    // Base imports
    assert!(output.contains("use serde::{Deserialize, Serialize}"));

    // Child imports (super() + own)
    assert!(output.contains("use rmcp::model::{CallToolRequestParams"));

    // Child body — param struct
    assert!(output.contains("pub struct GetUserParams"));
    assert!(output.contains("pub user_id: String"));

    // Child body — server struct
    assert!(output.contains("pub struct UserMcpServer"));
    assert!(output.contains("#[tool_router]"));
    assert!(output.contains("#[tool_handler"));

    // No Tera artifacts
    assert!(!output.contains("{{"), "no unclosed expressions in output");
    assert!(!output.contains("{%"), "no unrendered tags in output");
}

// ---------------------------------------------------------------------------
// Additional: Verify super() is called in all child imports blocks
// ---------------------------------------------------------------------------

#[test]
fn test_all_children_call_super_in_imports_block() {
    let root = workspace_root();
    let mcp_dir = root.join("crates/ggen-core/templates/mcp-server");
    if !mcp_dir.exists() {
        return;
    }

    for entry in WalkDir::new(&mcp_dir)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().is_some_and(|ext| ext == "tera"))
    {
        if entry.file_name() == "_head.tera" {
            continue;
        }

        let content = std::fs::read_to_string(entry.path())
            .unwrap_or_else(|e| panic!("Cannot read {}: {}", entry.path().display(), e));

        assert!(
            content.contains("{% block imports %}"),
            "{} must define an imports block",
            entry.path().display()
        );
        assert!(
            content.contains("{{ super() }}"),
            "{} must call super() in imports block to include base imports",
            entry.path().display()
        );
    }
}
