#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::needless_raw_string_hashes,
    clippy::duration_suboptimal_units,
    clippy::branches_sharing_code,
    clippy::used_underscore_binding,
    clippy::single_char_pattern,
    clippy::ignore_without_reason,
    clippy::cloned_ref_to_slice_refs,
    clippy::doc_overindented_list_items,
    clippy::match_wildcard_for_single_variants,
    clippy::ignored_unit_patterns,
    clippy::needless_collect,
    clippy::unnecessary_map_or,
    clippy::manual_flatten,
    clippy::manual_strip,
    clippy::future_not_send,
    clippy::unnested_or_patterns,
    clippy::no_effect_underscore_binding,
    clippy::literal_string_with_formatting_args
)]
//! Integration tests for μ₄: Code Canonicalization
//!
//! These tests verify the canonicalization functionality for A2A-RS integration.

use ggen_core::codegen::canonicalize::{
    canonicalize, canonicalize_a2a, canonicalize_file, canonicalize_rust_quick, CanonicalizeOptions,
};
use std::path::Path;

#[test]
fn test_canonicalize_basic_rust() {
    let input = r#"use std::b::B;
use std::a::A;
fn main() { println!("hello"); }"#;

    let options = CanonicalizeOptions::new()
        .with_sort_imports(true)
        .with_normalize_line_endings(true);

    let result = canonicalize(input, &options).unwrap();

    // std::a should come before std::b
    let a_pos = result.find("use std::a").unwrap();
    let b_pos = result.find("use std::b").unwrap();
    assert!(a_pos < b_pos);
}

#[test]
fn test_canonicalize_line_endings() {
    let input = "hello\r\nworld\r";
    let options = CanonicalizeOptions::new().with_normalize_line_endings(true);
    let result = canonicalize(input, &options).unwrap();
    assert_eq!(result, "hello\nworld\n");
}

#[test]
fn test_canonicalize_trailing_whitespace() {
    let input = "hello   \nworld  \n";
    let options = CanonicalizeOptions::new().with_trim_trailing_whitespace(true);
    let result = canonicalize(input, &options).unwrap();
    assert_eq!(result, "hello\nworld\n");
}

#[test]
fn test_canonicalize_inject_header() {
    let input = "fn main() {}\n";
    let options = CanonicalizeOptions::new().with_inject_header(true);
    let result = canonicalize(input, &options).unwrap();
    assert!(result.contains("DO NOT EDIT"));
    assert!(result.contains("Generated by ggen"));
}

#[test]
fn test_canonicalize_preserves_existing_header() {
    let input = "// DO NOT EDIT this file\nfn main() {}\n";
    let options = CanonicalizeOptions::new().with_inject_header(true);
    let result = canonicalize(input, &options).unwrap();
    // Should not duplicate the header
    let count = result.matches("DO NOT EDIT").count();
    assert_eq!(count, 1);
}

#[test]
fn test_canonicalize_import_grouping() {
    let input = r#"
use crate::module::Struct;
use std::collections::HashMap;
use external_crate::Trait;
use std::vec::Vec;
use crate::module::Type;
"#;

    let options = CanonicalizeOptions::new().with_sort_imports(true);
    let result = canonicalize(input, &options).unwrap();

    // Check that imports are grouped: std → external → internal
    let lines: Vec<&str> = result.lines().collect();
    let mut std_idx = None;
    let mut external_idx = None;
    let mut internal_idx = None;

    for (i, line) in lines.iter().enumerate() {
        if line.contains("use std::collections") {
            std_idx = Some(i);
        }
        if line.contains("use std::vec") {
            // vec should be after collections
            assert!(std_idx.unwrap_or(0) < i);
        }
        if line.contains("use external_crate") {
            external_idx = Some(i);
        }
        if line.contains("use crate::module") && internal_idx.is_none() {
            internal_idx = Some(i);
        }
    }

    // Verify ordering: std < external < internal
    if let (Some(std), Some(ext), Some(int)) = (std_idx, external_idx, internal_idx) {
        assert!(std < ext, "std imports should come before external");
        assert!(ext < int, "external imports should come before internal");
    }
}

#[test]
fn test_canonicalize_a2a_standard() {
    let input = r#"use std::collections::HashMap;
use std::vec::Vec;

fn main() {}
"#;

    let result = canonicalize_a2a(input).unwrap();

    // Should have header
    assert!(result.contains("DO NOT EDIT"));
    assert!(result.contains("Generated by ggen"));

    // Should maintain proper ordering
    let hash_pos = result.find("std::collections::HashMap").unwrap();
    let vec_pos = result.find("std::vec::Vec").unwrap();
    assert!(hash_pos < vec_pos);
}

#[test]
fn test_canonicalize_quick() {
    let input = r#"use std::b::B;
use std::a::A;
"#;

    let result = canonicalize_rust_quick(input).unwrap();

    // std::a should come before std::b
    let a_pos = result.find("use std::a").unwrap();
    let b_pos = result.find("use std::b").unwrap();
    assert!(a_pos < b_pos);

    // Should end with newline
    assert!(result.ends_with('\n'));
}

#[test]
fn test_canonicalize_file_by_extension() {
    let rs_content = "use std::b; use std::a;";
    let json_content = r#"{"b":1,"a":2}"#;
    let toml_content = "[package]\r\nname=\"test\"";

    let options = CanonicalizeOptions::new()
        .with_sort_imports(true)
        .with_normalize_line_endings(true);

    // Test .rs file
    let rs_result = canonicalize_file(Path::new("test.rs"), rs_content, &options).unwrap();
    assert!(rs_result.contains("use std::a"));

    // Test .json file
    let json_result = canonicalize_file(Path::new("test.json"), json_content, &options).unwrap();
    assert!(json_result.contains("\n")); // Pretty printed

    // Test .toml file
    let toml_result = canonicalize_file(Path::new("test.toml"), toml_content, &options).unwrap();
    assert!(!toml_result.contains("\r\n"));
}

#[test]
fn test_canonicalize_final_newline() {
    let input = "fn main() {}";
    let options = CanonicalizeOptions::new();
    let result = canonicalize(input, &options).unwrap();
    assert!(result.ends_with('\n'));
}

#[test]
fn test_canonicalize_preserves_shebang() {
    let input = "#!/usr/bin/env rust-script\nfn main() {}\n";
    let options = CanonicalizeOptions::new().with_inject_header(true);
    let result = canonicalize(input, &options).unwrap();

    // Shebang should be first
    assert!(result.starts_with("#!/usr/bin/env rust-script"));

    // Header should come after shebang
    assert!(result.contains("DO NOT EDIT"));

    // Content should be preserved
    assert!(result.contains("fn main()"));
}

#[test]
fn test_import_complex_paths() {
    let input = r#"
use std::sync::Arc;
use std::collections::HashMap;
use crate::module::inner::Struct;
use crate::module::Type;
"#;

    let options = CanonicalizeOptions::new().with_sort_imports(true);
    let result = canonicalize(input, &options).unwrap();

    // std imports should come before crate imports
    let std_pos = result.find("use std::").unwrap();
    let crate_pos = result.find("use crate::").unwrap();
    assert!(std_pos < crate_pos);
}

#[test]
fn test_whitespace_normalization() {
    let input = "  hello  \n\tworld\t\n  test  ";
    let options = CanonicalizeOptions::new()
        .with_trim_trailing_whitespace(true)
        .with_normalize_line_endings(true);
    let result = canonicalize(input, &options).unwrap();
    assert_eq!(result, "  hello\n\tworld\n  test\n");
}
